/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.Arrays;


public class MessageUtilsTest {

}
